<script>
var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    return reject(new Error('erra'));
  });
};

someAsyncThing().then(res=>console.log(res)).catch(res=> console.log(res))
</script>